version: '2'
services:
  front:
    build: ./front
    ports:
      - "4200:4200"
    depends_on:
      - back
  back:
    image: gtaques/universitycrud_flas
    ports: 
      - "5000:5000"
    depends_on: 
        - db
  db:
    image: postgres
    ports:
      - "5432:5432"